### ISSUE TITLE
Free models!! https://openrouter.ai -  There was an error processing your request.

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#191]
Hello,

I wanted to add an LLM from https://openrouter.ai/

When I test in the Playground, I get this message and then nothing:

There was an error processing your request.

The advantage of this provider is that they have free models, like:

Us: Capybara 7B
Mistral 7B Instruct
Hugging Face: Zephyr 7B
OpenChat 3.5
Cinematika 7B

Thanks for your help

**Comment by n4ze3m** [comment]
Hey, can you check the logs?

**Comment by comeback01** [comment]
Hello,

I use this address https://openrouter.ai/api/v1.

First I created a new key, then I used one that works in another program.

The problem is still there.

Here is the log:

`dialoqbase       | provider local
dialoqbase       | modelName gryphe/mythomist-7b
dialoqbase       | using local
dialoqbase       | Error: OpenAI or Azure OpenAI API key not found
dialoqbase       |     at new ChatOpenAI (/app/node_modules/@langchain/openai/dist/chat_models.cjs:329:19)
dialoqbase       |     at chatModelProvider (/app/utils/models.js:68:20)
dialoqbase       |     at Object.chatRequestStreamHandler (/app/routes/api/v1/bot/playground/handlers/chat.handler.js:308:62)
`

**Comment by n4ze3m** [comment]
Hey, there is an issue with the core package; that's why it's throwing an error for now. Can you add this to your .env file?

```
OPENAI_API_KEY="temp"
```

It will resolve the OpenRouter issue.

**Comment by comeback01** [comment]
Hello,

Thank you it works, but can I put an openAI key or not for now?

Thanks

**Comment by n4ze3m** [comment]
Hey, If you want to use OpenAI models, then use your actual OpenAI key. If not, just add a random value, and that's all. This issue will be fixed in upcoming updates

**Comment by comeback01** [comment]
Thank you, everything works,

I recommend that you add OpenRouteur, with a gift image for the free templates.

This will increase the popularity of your excellent work!
![Capture d'écran 2024-01-11 134140](https://github.com/n4ze3m/dialoqbase/assets/17897116/4556dc8c-14ff-4bb8-b779-781db455072c)
