### ISSUE TITLE
I get an error. 

### ISSUE THREAD

**Issue by PeterBusalov** [n4ze3m/dialoqbase#253]
Hi Nazim, please help me! I updated the program. When I run it through docker, I get an error : No pending migrations to apply.
Running seed command `ts-node prisma/seed.ts` ...
Seeding new models...

🌱  The seed command has been executed.
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.<anonymous> (/app/app.js:78:37)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at requireServerPluginFromPath (/app/node_modules/fastify-cli/util.js:79:20)
    at async runFastify (/app/node_modules/fastify-cli/start.js:90:12)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
yarn run v1.22.19
$ npx prisma migrate deploy && npx prisma db seed && fastify start app.js
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "dialoqbase", schema "public" at "dialoqbase-pg:5432"

32 migrations found in prisma/migrations

No pending migrations to apply.
Running seed command `ts-node prisma/seed.ts` ...

**Comment by n4ze3m** [comment]
Yes, this issue has been identified, and a patch has been released. It is currently being built. Sorry about it.

**Comment by n4ze3m** [comment]
The patch has been released. Please repull the image. Let me know if you face any issues
