### ISSUE TITLE
Since the update, the bots are no longer working, but...

### ISSUE THREAD

**Issue by comeback01** [n4ze3m/dialoqbase#258]
As I wrote in the title, since the update, none of the bots are working. There are no errors in the logs, which remain on "Connecting to database..."

I had the idea to do a test on Telegram and I got the message "Oops! Embedding not found".

It's true that I changed the API and I forgot to put an Embedding model.

I fixed that, created a new bot and it's working.

My problem is that for the existing bots, I can't change the model and they don't work.

How can I fix this?

Thank you

![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/f30d3b06-b2e0-41ce-9db8-014304168344)

**Comment by n4ze3m** [comment]
Hey, sorry about that. Which version did you update from to get to the latest one? Also, in Settings > Models > Embedding Models, is your 'dialoqbase_eb_text-embedding-ada-002' model disabled?

**Comment by comeback01** [comment]
I put the OpenAI model, because I don't see your, since the update it has disappeared.

I'll show you the screenshots

![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/dd3ca902-772e-4515-9f3a-8db22e68b817)
![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/d0759ca0-64b8-4482-8429-75a9e1eab62d)
![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/9a5fa2f0-4e86-4e03-b095-82b2e94b571d)
![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/ef6f7a5d-f1e8-4e9a-be20-a08b0a062a83)

**Comment by n4ze3m** [comment]
Hey, please enable this model; it will work fine :) 

![image](https://github.com/n4ze3m/dialoqbase/assets/39720973/48225279-a9c9-4612-99fc-08e2f1b45ecd)

**Comment by comeback01** [comment]
I added the template and if I create a new bot, no problem it works.

But with the old bot it doesn't work, I always have the same problem.

That's because the model isn't there and you can't change it.

Why isn't the model there?

![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/4025bcaf-6cd6-42f3-a233-0be90124ce81)

**Comment by n4ze3m** [comment]
> Hey, please enable this model; it will work fine :)
> 
> ![image](https://private-user-images.githubusercontent.com/39720973/326255683-48225279-a9c9-4612-99fc-08e2f1b45ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDk2NTcsIm5iZiI6MTcxNDMwOTM1NywicGF0aCI6Ii8zOTcyMDk3My8zMjYyNTU2ODMtNDgyMjUyNzktYTljOS00NjEyLTk5ZmMtMDhlMmYxYjQ1ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEzMDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWZkYjRlZWYzNjU3YTE3MjRmYzRlZjJhMjcyMGFhNWYxNTZlZGE2YmRhNmE3OTljZmI0NzNiZGIxMzEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TjZNpd0TgWK_4WY7jACBDhztxSocNLcXjeVVb9URE44)

Hey, could you go to Models > Embedding Model and enable `text-embedding-ada-002` please? It may fix the old bot issue

**Comment by n4ze3m** [comment]
> Hey, please enable this model; it will work fine :)
> 
> ![image](https://private-user-images.githubusercontent.com/39720973/326255683-48225279-a9c9-4612-99fc-08e2f1b45ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDk2NTcsIm5iZiI6MTcxNDMwOTM1NywicGF0aCI6Ii8zOTcyMDk3My8zMjYyNTU2ODMtNDgyMjUyNzktYTljOS00NjEyLTk5ZmMtMDhlMmYxYjQ1ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEzMDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWZkYjRlZWYzNjU3YTE3MjRmYzRlZjJhMjcyMGFhNWYxNTZlZGE2YmRhNmE3OTljZmI0NzNiZGIxMzEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TjZNpd0TgWK_4WY7jACBDhztxSocNLcXjeVVb9URE44)

Hey, dialoqbase_eb_text-embedding-ada-002 is the internal reference ID for text-embedding-ada-002. After referring to your screenshot, I think it's disabled, which is causing the issue. If you enable it from the embedding table, it may resolve all the issues.

**Comment by comeback01** [comment]
I had understood correctly, I activated it but it doesn't change anything.

But you can see from the image that it doesn't have the same name

![image](https://github.com/n4ze3m/dialoqbase/assets/17897116/b89d3a8d-1e36-48f0-8941-ad3cd2e021b7)

**Comment by n4ze3m** [comment]
That's weird. I will look into it. Can you check your bot to see if it's working now? It should have worked.

Unlike the chat model, you can't currently change embedding models due to dimensional issues. Doing so may completely break the bot, which is why this feature is disabled. I will look into a way to fix it

**Comment by comeback01** [comment]
Don't worry, I've deleted the docker and I'll start all over again.

It's not a bad thing

**Comment by n4ze3m** [comment]
In version 1.8.2, embedding models won't be disabled, but you can change them. Make sure you switch to the correct dimension model, or you'll need to retrain all the data sources

**Comment by comeback01** [comment]
Hello,

I started everything from scratch on another server.

Until yesterday, I had no problem, but now I again have the sentence "There was an error processing your request."

Here are the logs:

`dialoqbase           | clvjpwa9z000747auf7pxisw7
dialoqbase           | TypeError: query.join is not a function
dialoqbase           |     at DialoqbaseVectorStore.similaritySearchVectorWithScore (/app/utils/store.js:67:34)
dialoqbase           |     at DialoqbaseVectorStore.similaritySearch (/app/node_modules/@langchain/core/dist/vectorstores.cjs:108:36)
dialoqbase           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dialoqbase           |     at async VectorStoreRetriever.getRelevantDocuments (/app/node_modules/@langchain/core/dist/retrievers.cjs:70:29)
dialoqbase           |     at async VectorStoreRetriever._streamIterator (/app/node_modules/@langchain/core/dist/runnables/base.cjs:151:9)
dialoqbase           |     at async VectorStoreRetriever.transform (/app/node_modules/@langchain/core/dist/runnables/base.cjs:344:9)
dialoqbase           |     at async RunnableSequence._streamIterator (/app/node_modules/@langchain/core/dist/runnables/base.cjs:1084:30)
`

**Comment by n4ze3m** [comment]
hey, did you change the embedding model ?

**Comment by comeback01** [comment]
No, actually I created two bots that I use on Telegram, and when it didn't work, I didn't have a PC.

I think before the outage, I made a third bot based on a YouTube video, but there was a problem and I deleted the bot.

If necessary, I don't mind deleting the server again, it's quick.

**Comment by n4ze3m** [comment]
That is strange. I will try to reproduce this issue, since it's caused by the embedding model. By the way, which embedding model are you currently using

**Comment by comeback01** [comment]
I'm using text-embedding-3-large, but I have also tried text-embedding-3-small.

Since I'm using the program for two Telegram bots, I erased everything and started over again.

I don't want to touch it for now, and if the problem comes back, I'll give you full access and start over on another server.

Thank you for your help.
